//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trooper.WebResources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trooper.WebResources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.4 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///
        ////*! normalize.css v3.0.2 | MIT License | git.io/normalize */
        ///html {
        ///  font-family: sans-serif;
        ///  -webkit-text-size-adjust: 100%;
        ///      -ms-text-size-adjust: 100%;
        ///}
        ///body {
        ///  margin: 0;
        ///}
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///menu,
        ///nav,
        ///section,
        ///summary {
        ///  display: block;
        ///}
        ///audio,
        ///canvas,
        ///progress,
        ///video [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_css {
            get {
                return ResourceManager.GetString("bootstrap_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;version&quot;:3,&quot;sources&quot;:[&quot;bootstrap.css&quot;,&quot;less/normalize.less&quot;,&quot;less/print.less&quot;,&quot;less/glyphicons.less&quot;,&quot;less/scaffolding.less&quot;,&quot;less/mixins/vendor-prefixes.less&quot;,&quot;less/mixins/tab-focus.less&quot;,&quot;less/mixins/image.less&quot;,&quot;less/type.less&quot;,&quot;less/mixins/text-emphasis.less&quot;,&quot;less/mixins/background-variant.less&quot;,&quot;less/mixins/text-overflow.less&quot;,&quot;less/code.less&quot;,&quot;less/grid.less&quot;,&quot;less/mixins/grid.less&quot;,&quot;less/mixins/grid-framework.less&quot;,&quot;less/tables.less&quot;,&quot;less/mixins/table-row.less&quot;,&quot;less/forms.less&quot;,&quot;less/mixins/form [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_css_map {
            get {
                return ResourceManager.GetString("bootstrap_css_map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.3.4 (http://getbootstrap.com)
        /// * Copyright 2011-2015 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;var b=a.fn.jquery.split(&quot; &quot;)[0].split(&quot;.&quot;);if(b[0]&lt;2&amp;&amp;b[1]&lt;9||1==b[0]&amp;&amp;9==b[1]&amp;&amp;b[2]&lt;1)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery version 1.9.1 or higher&quot;)}(jQuery),+function(a){&quot;use strict&quot;;function b(){var a=docume [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_min_js {
            get {
                return ResourceManager.GetString("bootstrap_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot; &gt;
        ///&lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;metadata&gt;&lt;/metadata&gt;
        ///&lt;defs&gt;
        ///&lt;font id=&quot;glyphicons_halflingsregular&quot; horiz-adv-x=&quot;1200&quot; &gt;
        ///&lt;font-face units-per-em=&quot;1200&quot; ascent=&quot;960&quot; descent=&quot;-240&quot; /&gt;
        ///&lt;missing-glyph horiz-adv-x=&quot;500&quot; /&gt;
        ///&lt;glyph horiz-adv-x=&quot;0&quot; /&gt;
        ///&lt;glyph horiz-adv-x=&quot;400&quot; /&gt;
        ///&lt;glyph unicode=&quot; &quot; /&gt;
        ///&lt;glyph unicode=&quot;*&quot; d=&quot;M600 1100q15 0 34 -1.5t30 -3.5l11 -1q10 -2 17.5  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GlyphiconsHalflingsReguarSvg {
            get {
                return ResourceManager.GetString("GlyphiconsHalflingsReguarSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularEot {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularEot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularTtf {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularTtf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularWoff {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularWoff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularWoff2 {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularWoff2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///* jquery.inputmask.js
        ///* http://github.com/RobinHerbots/jquery.inputmask
        ///* Copyright (c) 2010 - 2015 Robin Herbots
        ///* Licensed under the MIT license (http://www.opensource.org/licenses/mit-license.php)
        ///* Version: 3.1.62
        ///*/
        ///!function(factory) {
        ///    &quot;function&quot; == typeof define &amp;&amp; define.amd ? define([ &quot;jquery&quot; ], factory) : factory(jQuery);
        ///}(function($) {
        ///    function isInputEventSupported(eventName) {
        ///        var el = document.createElement(&quot;input&quot;), evName = &quot;on&quot; + eventName, isSupported = evName in el;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_inputmask_js {
            get {
                return ResourceManager.GetString("jquery_inputmask_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v2.1.3 | (c) 2005, 2014 jQuery Foundation, Inc. | jquery.org/license */
        ///!function(a,b){&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){var c=[],d=c.slice,e=c.concat,f=c.push,g=c.indexOf,h={},i=h.toString,j=h.hasOwnProperty,k={},l=a.document,m=&quot;2.1.3&quot;,n=function(a,b){return new n.fn.init(a,b)},o=/^[ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_min_js {
            get {
                return ResourceManager.GetString("jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery UI Bootstrap (0.5)
        /// * http://addyosmani.github.com/jquery-ui-bootstrap
        /// *
        /// * Copyright 2012 - 2013, Addy Osmani
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// *
        /// * Portions copyright jQuery UI &amp; Twitter Bootstrap
        /// */
        ///
        ///
        ////* Layout helpers
        ///----------------------------------*/
        ///.ui-helper-hidden { display: none; }
        ///.ui-helper-hidden-accessible { 
        ///  border: 0; clip: rect(0 0 0 0);
        ///  height: 1px; 
        ///  margin: -1px; 
        ///  overflow: hidden; 
        ///  padding: 0; 
        ///  position: absolute [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_ui_bootstrap_theme_css {
            get {
                return ResourceManager.GetString("jquery_ui_bootstrap_theme_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.11.4 - 2015-03-11
        ///* http://jqueryui.com
        ///* Includes: core.js, widget.js, mouse.js, position.js, accordion.js, autocomplete.js, button.js, datepicker.js, dialog.js, draggable.js, droppable.js, effect.js, effect-blind.js, effect-bounce.js, effect-clip.js, effect-drop.js, effect-explode.js, effect-fade.js, effect-fold.js, effect-highlight.js, effect-puff.js, effect-pulsate.js, effect-scale.js, effect-shake.js, effect-size.js, effect-slide.js, effect-transfer.js, menu.js, progressbar.js, resiz [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_ui_min_js {
            get {
                return ResourceManager.GetString("jquery_ui_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //! moment.js
        /////! version : 2.10.2
        /////! authors : Tim Wood, Iskren Chernev, Moment.js contributors
        /////! license : MIT
        /////! momentjs.com
        ///
        ///(function (global, factory) {
        ///    typeof exports === &apos;object&apos; &amp;&amp; typeof module !== &apos;undefined&apos; ? module.exports = factory() :
        ///    typeof define === &apos;function&apos; &amp;&amp; define.amd ? define(factory) :
        ///    global.moment = factory()
        ///}(this, function () { &apos;use strict&apos;;
        ///
        ///    var hookCallback;
        ///
        ///    function utils_hooks__hooks () {
        ///        return hookCallback.apply(null, arguments);
        ///    }
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string moment_js {
            get {
                return ResourceManager.GetString("moment_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_flat_0_aaaaaa_40x100_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_flat_0_aaaaaa_40x100_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_glass_55_fbf9ee_1x400_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_55_fbf9ee_1x400_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_glass_65_ffffff_1x400_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_65_ffffff_1x400_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_glass_75_dadada_1x400_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_dadada_1x400_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_glass_75_e6e6e6_1x400_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_e6e6e6_1x400_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_glass_75_ffffff_1x400_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_glass_75_ffffff_1x400_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_highlight_soft_75_cccccc_1x100_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_highlight_soft_75_cccccc_1x100_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_bg_inset_soft_95_fef1ec_1x100_png {
            get {
                object obj = ResourceManager.GetObject("ui_bg_inset_soft_95_fef1ec_1x100_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_icons_222222_256x240_png {
            get {
                object obj = ResourceManager.GetObject("ui_icons_222222_256x240_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_icons_2e83ff_256x240_png {
            get {
                object obj = ResourceManager.GetObject("ui_icons_2e83ff_256x240_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_icons_454545_256x240_png {
            get {
                object obj = ResourceManager.GetObject("ui_icons_454545_256x240_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_icons_888888_256x240_png {
            get {
                object obj = ResourceManager.GetObject("ui_icons_888888_256x240_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_icons_cd0a0a_256x240_png {
            get {
                object obj = ResourceManager.GetObject("ui_icons_cd0a0a_256x240_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ui_icons_f6cf3b_256x240_png {
            get {
                object obj = ResourceManager.GetObject("ui_icons_f6cf3b_256x240_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
