//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductInShop", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Testing.CustomShopApi.Business.Mo" +
        "del")]
    [System.SerializableAttribute()]
    public partial class ProductInShop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShopIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bin {
            get {
                return this.BinField;
            }
            set {
                if ((object.ReferenceEquals(this.BinField, value) != true)) {
                    this.BinField = value;
                    this.RaisePropertyChanged("Bin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Identity", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Security")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco))]
    public partial class Identity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CultureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Culture {
            get {
                return this.CultureField;
            }
            set {
                if ((object.ReferenceEquals(this.CultureField, value) != true)) {
                    this.CultureField = value;
                    this.RaisePropertyChanged("Culture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Session {
            get {
                return this.SessionField;
            }
            set {
                if ((this.SessionField.Equals(value) != true)) {
                    this.SessionField = value;
                    this.RaisePropertyChanged("Session");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CHpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CHpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Identity {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.AddResponseOfShop5WpXDBwg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CBpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.AddSomeResponseOfShop5WpXDBwg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CCpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.SingleResponseOfboolean))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ManyResponseOfShop5WpXDBwg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.SingleResponseOfShop5WpXDBwg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CApoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.SingleResponseOfProduct5WpXDBwg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.MyProduct))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ProductInShop))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CDpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CGpoco))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Identity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.RequestArgOfShop5WpXDBwg))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Product))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Search))]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool OkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool WarnField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Ok {
            get {
                return this.OkField;
            }
            set {
                if ((this.OkField.Equals(value) != true)) {
                    this.OkField = value;
                    this.RaisePropertyChanged("Ok");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Warn {
            get {
                return this.WarnField;
            }
            set {
                if ((this.WarnField.Equals(value) != true)) {
                    this.WarnField = value;
                    this.RaisePropertyChanged("Warn");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddResponseOfShop5WpXDBwg", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CBpoco))]
    public partial class AddResponseOfShop5WpXDBwg : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CBpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CBpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.AddResponseOfShop5WpXDBwg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddSomeResponseOfShop5WpXDBwg", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CCpoco))]
    public partial class AddSomeResponseOfShop5WpXDBwg : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CCpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CCpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.AddSomeResponseOfShop5WpXDBwg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleResponseOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco))]
    public partial class SingleResponseOfboolean : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Item {
            get {
                return this.ItemField;
            }
            set {
                if ((this.ItemField.Equals(value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CEpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CEpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.SingleResponseOfboolean {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ManyResponseOfShop5WpXDBwg", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco))]
    public partial class ManyResponseOfShop5WpXDBwg : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CFpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CFpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ManyResponseOfShop5WpXDBwg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleResponseOfShop5WpXDBwg", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CApoco))]
    public partial class SingleResponseOfShop5WpXDBwg : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CApoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CApoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.SingleResponseOfShop5WpXDBwg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleResponseOfProduct5WpXDBwg", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Response")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.MyProduct))]
    public partial class SingleResponseOfProduct5WpXDBwg : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Response {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Product ItemField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Product Item {
            get {
                return this.ItemField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemField, value) != true)) {
                    this.ItemField = value;
                    this.RaisePropertyChanged("Item");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyProduct", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class MyProduct : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.SingleResponseOfProduct5WpXDBwg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CDpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CDpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.RequestArgOfShop5WpXDBwg {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CGpoco", Namespace="http://schemas.datacontract.org/2004/07/Trooper.DynamicServiceHost.DynamicHost.Tr" +
        "ooperTestingCustomShopApiBusinessOperation")]
    [System.SerializableAttribute()]
    public partial class CGpoco : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Search {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestArgOfShop5WpXDBwg", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Security")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CDpoco))]
    public partial class RequestArgOfShop5WpXDBwg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Product", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Testing.ShopModel.Poco")]
    [System.SerializableAttribute()]
    public partial class Product : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ColourField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Colour {
            get {
                return this.ColourField;
            }
            set {
                if ((object.ReferenceEquals(this.ColourField, value) != true)) {
                    this.ColourField = value;
                    this.RaisePropertyChanged("Colour");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Shop", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Testing.ShopModel.Poco")]
    [System.SerializableAttribute()]
    public partial class Shop : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ShopIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ShopId {
            get {
                return this.ShopIdField;
            }
            set {
                if ((this.ShopIdField.Equals(value) != true)) {
                    this.ShopIdField = value;
                    this.RaisePropertyChanged("ShopId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Search", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Thorny.Business.Operation.Core")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CGpoco))]
    public partial class Search : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SkipItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TakeItemsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SkipItems {
            get {
                return this.SkipItemsField;
            }
            set {
                if ((this.SkipItemsField.Equals(value) != true)) {
                    this.SkipItemsField = value;
                    this.RaisePropertyChanged("SkipItems");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TakeItems {
            get {
                return this.TakeItemsField;
            }
            set {
                if ((this.TakeItemsField.Equals(value) != true)) {
                    this.TakeItemsField = value;
                    this.RaisePropertyChanged("TakeItems");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs", ConfigurationName="CustomShopServiceReference.IShopBo")]
    public interface IShopBo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/SaveProduct", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/SaveProductResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.MyProduct SaveProduct(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ProductInShop productInShop, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/SaveProduct", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/SaveProductResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.MyProduct> SaveProductAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ProductInShop productInShop, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/Add", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/AddResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CBpoco Add(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/Add", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/AddResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CBpoco> AddAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/AddSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/AddSomeResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CCpoco AddSome(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] items, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/AddSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/AddSomeResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CCpoco> AddSomeAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] items, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/IsAllowed", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/IsAllowedResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco IsAllowed(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CDpoco argument, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/IsAllowed", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/IsAllowedResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco> IsAllowedAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CDpoco argument, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetAll", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetAllResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco GetAll(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetAll", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetAllResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco> GetAllAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetSomeResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco GetSome(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CGpoco search, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetSomeResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco> GetSomeAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CGpoco search, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetByKeyResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CApoco GetByKey(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/GetByKeyResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CApoco> GetByKeyAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/ExistsByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/ExistsByKeyResponse")]
        Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco ExistsByKey(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/ExistsByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShopApi.Business.Operation.ShopBoNs/I" +
            "ShopBo/ExistsByKeyResponse")]
        System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco> ExistsByKeyAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShopBoChannel : Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.IShopBo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShopBoClient : System.ServiceModel.ClientBase<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.IShopBo>, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.IShopBo {
        
        public ShopBoClient() {
        }
        
        public ShopBoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShopBoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopBoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShopBoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.MyProduct SaveProduct(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ProductInShop productInShop, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.SaveProduct(productInShop, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.MyProduct> SaveProductAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.ProductInShop productInShop, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.SaveProductAsync(productInShop, identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CBpoco Add(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.Add(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CBpoco> AddAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.AddAsync(item, identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CCpoco AddSome(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] items, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.AddSome(items, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CCpoco> AddSomeAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop[] items, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.AddSomeAsync(items, identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco IsAllowed(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CDpoco argument, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.IsAllowed(argument, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco> IsAllowedAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CDpoco argument, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.IsAllowedAsync(argument, identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco GetAll(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.GetAll(identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco> GetAllAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.GetAllAsync(identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco GetSome(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CGpoco search, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.GetSome(search, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CFpoco> GetSomeAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CGpoco search, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.GetSomeAsync(search, identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CApoco GetByKey(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.GetByKey(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CApoco> GetByKeyAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.GetByKeyAsync(item, identity);
        }
        
        public Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco ExistsByKey(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.ExistsByKey(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CEpoco> ExistsByKeyAsync(Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.Shop item, Trooper.Testing.CustomShopClientConsole.CustomShopServiceReference.CHpoco identity) {
            return base.Channel.ExistsByKeyAsync(item, identity);
        }
    }
}
