//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutletAddressSearch", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Testing.CustomShop.Api.Business.S" +
        "upport.OutletSupport")]
    [System.SerializableAttribute()]
    public partial class OutletAddressSearch : Trooper.Thorny.Business.Operation.Core.Search, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutletNameSearch", Namespace="http://schemas.datacontract.org/2004/07/Trooper.Testing.CustomShop.Api.Business.S" +
        "upport.OutletSupport")]
    [System.SerializableAttribute()]
    public partial class OutletNameSearch : Trooper.Thorny.Business.Operation.Core.Search, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
        "s", ConfigurationName="OutletBoServiceReference.IOutletBo")]
    public interface IOutletBo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/Add", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/AddResponse")]
        Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet> Add(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/Add", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/AddResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>> AddAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/AddSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/AddSomeResponse")]
        Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet> AddSome(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/AddSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/AddSomeResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>> AddSomeAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/IsAllowed", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/IsAllowedResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Message[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.MessageAlertLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.SaveChangeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Security.Identity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Operation.Core.Search))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.ShopPoco.Outlet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.ShopPoco.Outlet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch))]
        Trooper.Thorny.Business.Response.SingleResponse<bool> IsAllowed(Trooper.Thorny.Business.Security.RequestArg<Trooper.Testing.ShopPoco.Outlet> argument, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/IsAllowed", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/IsAllowedResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<bool>> IsAllowedAsync(Trooper.Thorny.Business.Security.RequestArg<Trooper.Testing.ShopPoco.Outlet> argument, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSession", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSessionResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Message[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.MessageAlertLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.SaveChangeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Security.Identity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Operation.Core.Search))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.ShopPoco.Outlet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.ShopPoco.Outlet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Security.RequestArg<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch))]
        object GetSession(Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSession", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSessionResponse")]
        System.Threading.Tasks.Task<object> GetSessionAsync(Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetAll", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetAllResponse")]
        Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> GetAll(Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetAll", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetAllResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> GetAllAsync(Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetByKeyResponse")]
        Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet> GetByKey(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetByKeyResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>> GetByKeyAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/ExistsByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/ExistsByKeyResponse")]
        Trooper.Thorny.Business.Response.SingleResponse<bool> ExistsByKey(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/ExistsByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/ExistsByKeyResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<bool>> ExistsByKeyAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteByKeyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>))]
        Trooper.Thorny.Business.Response.Response DeleteByKey(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteByKeyResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.Response> DeleteByKeyAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteSomeByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteSomeByKeyResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>))]
        Trooper.Thorny.Business.Response.Response DeleteSomeByKey(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteSomeByKey", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/DeleteSomeByKeyResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.Response> DeleteSomeByKeyAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/Update", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/UpdateResponse")]
        Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet> Update(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/Update", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/UpdateResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>> UpdateAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/UpdateSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/UpdateSomeResponse")]
        Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> UpdateSome(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/UpdateSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/UpdateSomeResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> UpdateSomeAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/Save", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/SaveResponse")]
        Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet> Save(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/Save", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/SaveResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>> SaveAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/SaveSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/SaveSomeResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Response))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Message[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.Message))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<bool>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.MessageAlertLevel))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.SaveChangeType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Security.Identity))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Operation.Core.Search))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.ShopPoco.Outlet))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.ShopPoco.Outlet[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Thorny.Business.Security.RequestArg<Trooper.Testing.ShopPoco.Outlet>))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch))]
        Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet> SaveSome(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/SaveSome", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/SaveSomeResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet>> SaveSomeAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletAddressSearch", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletAddressSearchResponse")]
        Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> GetSomeByOutletAddressSearch(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch search, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletAddressSearch", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletAddressSearchResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> GetSomeByOutletAddressSearchAsync(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch search, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletNameSearch", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletNameSearchResponse")]
        Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> GetSomeByOutletNameSearch(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch search, Trooper.Thorny.Business.Security.Identity identity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletNameSearch", ReplyAction="http://localhost:8000/Trooper.Testing.CustomShop.Api.Business.Operation.OutletBoN" +
            "s/IOutletBo/GetSomeByOutletNameSearchResponse")]
        System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> GetSomeByOutletNameSearchAsync(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch search, Trooper.Thorny.Business.Security.Identity identity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOutletBoChannel : Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.IOutletBo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OutletBoClient : System.ServiceModel.ClientBase<Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.IOutletBo>, Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.IOutletBo {
        
        public OutletBoClient() {
        }
        
        public OutletBoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OutletBoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutletBoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OutletBoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet> Add(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.Add(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.AddResponse<Trooper.Testing.ShopPoco.Outlet>> AddAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.AddAsync(item, identity);
        }
        
        public Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet> AddSome(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.AddSome(items, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.AddSomeResponse<Trooper.Testing.ShopPoco.Outlet>> AddSomeAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.AddSomeAsync(items, identity);
        }
        
        public Trooper.Thorny.Business.Response.SingleResponse<bool> IsAllowed(Trooper.Thorny.Business.Security.RequestArg<Trooper.Testing.ShopPoco.Outlet> argument, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.IsAllowed(argument, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<bool>> IsAllowedAsync(Trooper.Thorny.Business.Security.RequestArg<Trooper.Testing.ShopPoco.Outlet> argument, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.IsAllowedAsync(argument, identity);
        }
        
        public object GetSession(Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetSession(identity);
        }
        
        public System.Threading.Tasks.Task<object> GetSessionAsync(Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetSessionAsync(identity);
        }
        
        public Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> GetAll(Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetAll(identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> GetAllAsync(Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetAllAsync(identity);
        }
        
        public Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet> GetByKey(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetByKey(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>> GetByKeyAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetByKeyAsync(item, identity);
        }
        
        public Trooper.Thorny.Business.Response.SingleResponse<bool> ExistsByKey(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.ExistsByKey(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<bool>> ExistsByKeyAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.ExistsByKeyAsync(item, identity);
        }
        
        public Trooper.Thorny.Business.Response.Response DeleteByKey(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.DeleteByKey(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.Response> DeleteByKeyAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.DeleteByKeyAsync(item, identity);
        }
        
        public Trooper.Thorny.Business.Response.Response DeleteSomeByKey(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.DeleteSomeByKey(items, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.Response> DeleteSomeByKeyAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.DeleteSomeByKeyAsync(items, identity);
        }
        
        public Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet> Update(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.Update(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SingleResponse<Trooper.Testing.ShopPoco.Outlet>> UpdateAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.UpdateAsync(item, identity);
        }
        
        public Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> UpdateSome(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.UpdateSome(items, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> UpdateSomeAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.UpdateSomeAsync(items, identity);
        }
        
        public Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet> Save(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.Save(item, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SaveResponse<Trooper.Testing.ShopPoco.Outlet>> SaveAsync(Trooper.Testing.ShopPoco.Outlet item, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.SaveAsync(item, identity);
        }
        
        public Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet> SaveSome(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.SaveSome(items, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.SaveSomeResponse<Trooper.Testing.ShopPoco.Outlet>> SaveSomeAsync(Trooper.Testing.ShopPoco.Outlet[] items, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.SaveSomeAsync(items, identity);
        }
        
        public Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> GetSomeByOutletAddressSearch(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch search, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetSomeByOutletAddressSearch(search, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> GetSomeByOutletAddressSearchAsync(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletAddressSearch search, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetSomeByOutletAddressSearchAsync(search, identity);
        }
        
        public Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet> GetSomeByOutletNameSearch(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch search, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetSomeByOutletNameSearch(search, identity);
        }
        
        public System.Threading.Tasks.Task<Trooper.Thorny.Business.Response.ManyResponse<Trooper.Testing.ShopPoco.Outlet>> GetSomeByOutletNameSearchAsync(Trooper.Testing.CustomShop.Api.TestFromWs.OutletBoServiceReference.OutletNameSearch search, Trooper.Thorny.Business.Security.Identity identity) {
            return base.Channel.GetSomeByOutletNameSearchAsync(search, identity);
        }
    }
}
