//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trooper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trooper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CN.
        /// </summary>
        public static string ActiveDirectoryCn {
            get {
                return ResourceManager.GetString("ActiveDirectoryCn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to defaultNamingContext.
        /// </summary>
        public static string ActiveDirectoryDefaultNamingContext {
            get {
                return ResourceManager.GetString("ActiveDirectoryDefaultNamingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to department.
        /// </summary>
        public static string ActiveDirectoryDepartment {
            get {
                return ResourceManager.GetString("ActiveDirectoryDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        public static string ActiveDirectoryDescription {
            get {
                return ResourceManager.GetString("ActiveDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to displayName.
        /// </summary>
        public static string ActiveDirectoryDisplayName {
            get {
                return ResourceManager.GetString("ActiveDirectoryDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DN.
        /// </summary>
        public static string ActiveDirectoryDn {
            get {
                return ResourceManager.GetString("ActiveDirectoryDn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dnsHostName.
        /// </summary>
        public static string ActiveDirectoryDnsHostName {
            get {
                return ResourceManager.GetString("ActiveDirectoryDnsHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to givenName.
        /// </summary>
        public static string ActiveDirectoryGivenName {
            get {
                return ResourceManager.GetString("ActiveDirectoryGivenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to initials.
        /// </summary>
        public static string ActiveDirectoryInitials {
            get {
                return ResourceManager.GetString("ActiveDirectoryInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://{0}/{1}.
        /// </summary>
        public static string ActiveDirectoryLdapPathFormat {
            get {
                return ResourceManager.GetString("ActiveDirectoryLdapPathFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mail.
        /// </summary>
        public static string ActiveDirectoryMail {
            get {
                return ResourceManager.GetString("ActiveDirectoryMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to memberof.
        /// </summary>
        public static string ActiveDirectoryMemberOf {
            get {
                return ResourceManager.GetString("ActiveDirectoryMemberOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleName.
        /// </summary>
        public static string ActiveDirectoryMiddleName {
            get {
                return ResourceManager.GetString("ActiveDirectoryMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mobile.
        /// </summary>
        public static string ActiveDirectoryMobile {
            get {
                return ResourceManager.GetString("ActiveDirectoryMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to physicalDeliveryOfficeName.
        /// </summary>
        public static string ActiveDirectoryPhysicalDeliveryOfficeName {
            get {
                return ResourceManager.GetString("ActiveDirectoryPhysicalDeliveryOfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP://RootDSE.
        /// </summary>
        public static string ActiveDirectoryRoot {
            get {
                return ResourceManager.GetString("ActiveDirectoryRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (SAMAccountName={0}).
        /// </summary>
        public static string ActiveDirectorySamAccountFormat {
            get {
                return ResourceManager.GetString("ActiveDirectorySamAccountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn.
        /// </summary>
        public static string ActiveDirectorySn {
            get {
                return ResourceManager.GetString("ActiveDirectorySn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to telephoneNumber.
        /// </summary>
        public static string ActiveDirectoryTelephoneNumber {
            get {
                return ResourceManager.GetString("ActiveDirectoryTelephoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to userPrincipalName.
        /// </summary>
        public static string ActiveDirectoryUserPrincipalName {
            get {
                return ResourceManager.GetString("ActiveDirectoryUserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.1.1 (http://getbootstrap.com)
        /// * Copyright 2011-2014 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///
        ////*! normalize.css v3.0.0 | MIT License | git.io/normalize */
        ///html {
        ///  font-family: sans-serif;
        ///  -webkit-text-size-adjust: 100%;
        ///      -ms-text-size-adjust: 100%;
        ///}
        ///body {
        ///  margin: 0;
        ///}
        ///article,
        ///aside,
        ///details,
        ///figcaption,
        ///figure,
        ///footer,
        ///header,
        ///hgroup,
        ///main,
        ///nav,
        ///section,
        ///summary {
        ///  display: block;
        ///}
        ///audio,
        ///canvas,
        ///progress,
        ///video {
        ///  d [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_css {
            get {
                return ResourceManager.GetString("bootstrap_css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * Bootstrap v3.1.1 (http://getbootstrap.com)
        /// * Copyright 2011-2014 Twitter, Inc.
        /// * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        /// */
        ///if(&quot;undefined&quot;==typeof jQuery)throw new Error(&quot;Bootstrap&apos;s JavaScript requires jQuery&quot;);+function(a){&quot;use strict&quot;;function b(){var a=document.createElement(&quot;bootstrap&quot;),b={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;};for(var c in b)if(void 0!==a.s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string bootstrap_min_js {
            get {
                return ResourceManager.GetString("bootstrap_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapButton(id) {
        ///    return window[id + &apos;_BootstrapButton&apos;];
        ///}
        ///
        ///function BootstrapTextbox(params) {
        ///    this.id = params.id;
        ///    this.url = params.url;
        ///    this.targetNewWindow = params.targetNewWindow;
        ///   
        ///    $(document).ready($.proxy(this.init, this));
        ///};
        ///
        ///BootstrapTextbox.prototype.id = &apos;&apos;;
        ///
        ///BootstrapTextbox.prototype.url = &apos;&apos;;
        ///
        ///BootstrapTextbox.prototype.targetNewWindow = &apos;&apos;;
        ///
        ///BootstrapTextbox.prototype.getInput = function () {
        ///    return $(&apos;#&apos; + this.id);
        ///};
        ///
        ///Boo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapButton_js {
            get {
                return ResourceManager.GetString("BootstrapButton_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapCheckBox(params) {
        ///    this.id = params.id;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapCheckBox.prototype.id = &apos;&apos;;
        ///
        ///BootstrapCheckBox.prototype.warnOnLeave = true;
        ///
        ///BootstrapCheckBox.prototype.init = function () {
        ///    if (this.warnOnLeave) {
        ///        var bsf = GetBootstrapForm();
        ///        bsf.addVolatileField(this.inputId);
        ///    }
        ///};.
        /// </summary>
        public static string BootstrapCheckBox_js {
            get {
                return ResourceManager.GetString("BootstrapCheckBox_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapCheckBoxList(params) {
        ///    this.id = params.id;
        ///    this.name = params.name;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapCheckBoxList.prototype.id = &apos;&apos;;
        ///
        ///BootstrapCheckBoxList.prototype.name = &apos;&apos;;
        ///
        ///BootstrapCheckBoxList.prototype.warnOnLeave = true;
        ///
        ///BootstrapCheckBoxList.prototype.init = function () {
        ///    if (this.warnOnLeave) {
        ///        var bsf = GetBootstrapForm();
        ///
        ///        $(&apos;[name=&apos; + this.name + &apos;]&apos;).each(f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapCheckBoxList_js {
            get {
                return ResourceManager.GetString("BootstrapCheckBoxList_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapDateTimePicker(params) {
        ///    this.id = params.id;
        ///    this.format = params.format;
        ///    this.pickDate = params.pickDate;
        ///    this.pickTime = params.pickTime;
        ///    this.pickSeconds = params.pickSeconds;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///    this.popoverPlacement = params.popoverPlacement;
        ///    this.timezone = params.timezone;
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapDateTimePicker.prototype.id = null;
        ///
        ///BootstrapDateTimePicker.prototype.format = null [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapDateTimePicker_js {
            get {
                return ResourceManager.GetString("BootstrapDateTimePicker_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bootstrapDateTimePicker table tbody tr td.day {
        ///    cursor: pointer;   
        ///}
        ///
        ///.bootstrapDateTimePicker table tr td.day:hover {
        ///    background: #333333;
        ///    color: #fff;
        ///}
        ///
        ///.bootstrapDateTimePicker table tr td,
        ///.bootstrapDateTimePicker table tr th {
        ///    font-size: 13px;
        ///}
        ///
        ///.bootstrapDateTimePicker .date-input::-ms-clear {
        ///    display: none;
        ///}
        ///
        ///.bootstrapDateTimePicker .month {
        ///    text-align: right;
        ///    font-weight: bold;
        ///}
        ///
        ///.bootstrapDateTimePicker .year {
        ///}
        ///             
        ///.bootstrapD [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapDateTimePicker_less {
            get {
                return ResourceManager.GetString("BootstrapDateTimePicker_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapForm() {
        ///    return window[&apos;bootstrapForm&apos;];
        ///}
        ///
        ///function BootstrapForm() {
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapForm.prototype.formIsDirty = false;
        ///
        ///BootstrapForm.prototype.init = function() {
        ///    
        ///};
        ///
        ////**
        /// * Indicates that the field (which can be a field id or jquery object) is volatile
        /// * and if it changes and the user has not saved the current record then an alert message
        /// * should be raised if the user attempts to leave the page.
        /// */
        ///Bootst [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapForm_js {
            get {
                return ResourceManager.GetString("BootstrapForm_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapHtml() {
        ///    return window[&apos;bootstrapHtml&apos;];
        ///}
        ///
        ///function BootstrapHtml() {
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapHtml.prototype.init = function () {
        ///    this.screenModeChangeEvents = new Array();
        ///    this.currentScreenMode = this.getScreenMode();
        ///
        ///    $(window).resize($.proxy(this.screenModeChange, this));
        ///};
        ///
        ////*
        /// * Provides the last recorded screen mode before the screen.
        /// */ 
        ///BootstrapHtml.prototype.currentScreenMode = &apos;&apos;;
        ///
        ////*
        /// * The array o [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapHtml_js {
            get {
                return ResourceManager.GetString("BootstrapHtml_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .form-group.has-error .input-group-btn button {
        ///    border-color: #b94a48;
        ///    color: #b94a48;
        ///}
        ///
        ///.control-group.has-error legend {
        ///    color: #b94a48;
        ///}
        ///
        ///.trooper.y-scrolling {
        ///        overflow-y: scroll;
        ///        border-top: 1px solid #e5e5e5;
        ///        border-left: 1px solid #e5e5e5;
        ///        border-bottom: 1px solid #e5e5e5;
        ///        border-top-left-radius: 4px;
        ///        border-bottom-left-radius: 4px;
        ///        padding-left: 10px;
        ///    }
        ///
        ///fieldset {
        ///    legend {
        ///        line-height: 30px;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapHtmlHelper_less {
            get {
                return ResourceManager.GetString("BootstrapHtmlHelper_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapNumericBox(id) {
        ///    return window[id + &apos;_BootstrapTextbox&apos;];
        ///}
        ///
        ///function BootstrapNumericBox(params) {
        ///    this.id = params.id;
        ///    this.numericType = params.numericType;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///
        ///    this.minimum = parseFloat(params.minimum);
        ///
        ///    if (isNaN(this.minimum)) {
        ///        this.minimum = null;
        ///    }
        ///
        ///    this.maximum = parseFloat(params.maximum);
        ///
        ///    if (isNaN(this.maximum)) {
        ///        this.maximum = null;
        ///    }
        ///
        ///    this.decimalDigits = [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapNumericBox_js {
            get {
                return ResourceManager.GetString("BootstrapNumericBox_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapPanelGroup(params) {
        ///    this.id = params.id;
        ///    this.active = params.active;
        ///    this.hasErrors = params.hasErrors;
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapPanelGroup.prototype.id = &apos;&apos;;
        ///
        ///BootstrapPanelGroup.prototype.active = &apos;&apos;;
        ///
        ///BootstrapPanelGroup.prototype.hasErrors = false;
        ///
        ///BootstrapPanelGroup.prototype.init = function () {
        ///    $(&apos;#&apos; + this.id + &apos; .panel .panel-heading a&apos;).click($.proxy(this.panelOpened, this));
        ///
        ///    if (this.hasErrors) {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapPanelGroup_js {
            get {
                return ResourceManager.GetString("BootstrapPanelGroup_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapRadioList(params) {
        ///    this.id = params.id;
        ///    this.name = params.name;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapRadioList.prototype.id = &apos;&apos;;
        ///
        ///BootstrapRadioList.prototype.name = &apos;&apos;;
        ///
        ///BootstrapRadioList.prototype.warnOnLeave = true;
        ///
        ///BootstrapRadioList.prototype.init = function () {
        ///    if (this.warnOnLeave) {
        ///        var bsf = GetBootstrapForm();
        ///
        ///        $(&apos;[name=&quot;&apos; + this.name + &apos;&quot;]&apos;).each(function (inde [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapRadioList_js {
            get {
                return ResourceManager.GetString("BootstrapRadioList_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapSearchBox(id) {
        ///    return window[id + &apos;_BootstrapSearchBox&apos;];
        ///}
        ///
        ///function BootstrapSearchBox(params) {
        ///    this.inputName = params.inputName;
        ///    this.dataSourceUrl = params.dataSourceUrl;
        ///    this.searchTextField = params.searchTextField;
        ///    this.searchValueField = params.searchValueField;
        ///    this.selectedTextField = params.selectedTextField;
        ///    this.scrollHeight = params.scrollHeight;
        ///    this.popoverPlacement = params.popoverPlacement;
        ///    this.popoutWidth = params.po [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapSearchBox_js {
            get {
                return ResourceManager.GetString("BootstrapSearchBox_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .bs-search-box {
        ///    .popover-content {
        ///        padding: 0;
        ///
        ///        ul {
        ///            border: none;
        ///            outline: none;
        ///            width: 100%;
        ///            overflow-y: scroll;
        ///            margin: 0;
        ///            padding: 0;
        ///
        ///            li {
        ///                margin: 0;
        ///                padding: 2px 2px 2px 5px;
        ///                cursor: pointer;
        ///                border-bottom: 1px solid #e5e5e5;
        ///            }
        ///
        ///            li:hover {
        ///                background-color: #e3e3e3;
        ///          [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapSearchBox_less {
            get {
                return ResourceManager.GetString("BootstrapSearchBox_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapSelectList(params) {
        ///    this.id = params.id;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapSelectList.prototype.id = &apos;&apos;;
        ///
        ///BootstrapSelectList.prototype.warnOnLeave = true;
        ///
        ///BootstrapSelectList.prototype.init = function () {
        ///    if (this.warnOnLeave) {
        ///        var bsf = GetBootstrapForm();
        ///        bsf.addVolatileField(this.id);
        ///    }
        ///};.
        /// </summary>
        public static string BootstrapSelectList_js {
            get {
                return ResourceManager.GetString("BootstrapSelectList_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapTable(id) {
        ///    return window[&apos;bootstrapTable_&apos; + id];
        ///}
        ///
        ///function BootstrapTable(params) {
        ///    this.id = params.id;
        ///    this.rowSelectionMode = params.rowSelectionMode;
        ///    
        ///    this.rowSelected = new Array();
        ///    this.rowDblclicked = new Array();
        ///    this.rowUnselected = new Array();
        ///    this.selectedRows = new Array();
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapTable.prototype.id = null;
        ///
        ///BootstrapTable.prototype.rowSelectionMode = null;
        ///
        ////*
        ///*  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapTable_js {
            get {
                return ResourceManager.GetString("BootstrapTable_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table.table.trooper {
        ///
        ///    tbody tr td {
        ///        cursor: pointer;
        ///    }
        ///
        ///    tbody {
        ///        tr.bold td {
        ///            font-weight: bold;
        ///        }
        ///
        ///        tr.rule-over td {
        ///            border-top-width: 1px;
        ///            border-top-color: black;
        ///        }
        ///
        ///        tr.rule-over.rule-over-solid td {
        ///            border-top-style: solid;
        ///        }
        ///
        ///        tr.rule-over.rule-over-dashed td {
        ///            border-bottom-style: dashed;
        ///        }
        ///
        ///        tr.rule-under td {
        ///            border [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapTable_less {
            get {
                return ResourceManager.GetString("BootstrapTable_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function BootstrapTextareaBox(id) {
        ///    return window[id + &apos;_BootstrapTextareaBox&apos;];
        ///}
        ///
        ///function BootstrapTextareaBox(params) {
        ///    this.id = params.id;
        ///    this.maxLength = params.maxLength;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///   
        ///    $(document).ready($.proxy(this.init, this));
        ///};
        ///
        ///BootstrapTextareaBox.prototype.id = &apos;&apos;;
        ///
        ///BootstrapTextareaBox.prototype.maxLength = 0;
        ///
        ///BootstrapTextareaBox.prototype.warnOnLeave = true;
        ///
        ///BootstrapTextareaBox.prototype.getInput = function () {
        ///    r [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapTextareaBox_js {
            get {
                return ResourceManager.GetString("BootstrapTextareaBox_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapTextbox(id) {
        ///    return window[id + &apos;_BootstrapTextbox&apos;];
        ///}
        ///
        ///function BootstrapTextbox(params) {
        ///    this.id = params.id;
        ///    this.maxLength = params.maxLength;
        ///    this.warnOnLeave = params.warnOnLeave;
        ///   
        ///    $(document).ready($.proxy(this.init, this));
        ///};
        ///
        ///BootstrapTextbox.prototype.id = &apos;&apos;;
        ///
        ///BootstrapTextbox.prototype.maxLength = 0;
        ///
        ///BootstrapTextbox.prototype.warnOnLeave = true;
        ///
        ///BootstrapTextbox.prototype.getInput = function () {
        ///    return $(&apos;#&apos; + this.id);
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapTextBox_js {
            get {
                return ResourceManager.GetString("BootstrapTextBox_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /** 
        ///* --------------------------------------------------------------------------------------
        ///* &lt;copyright file=&quot;BootstrapUpload.js&quot; company=&quot;Trooper Inc&quot;&gt;
        ///*     Copyright (c) Trooper 2014 - Onwards
        ///* &lt;/copyright&gt;
        ///* --------------------------------------------------------------------------------------
        ///*/
        ///
        ///function GetBootstrapUpload(id) {
        ///    return window[id + &apos;_BootstrapUpload&apos;];
        ///}
        ///
        ////**
        /// * Turns a plain old upload form element into a bootstrap element 
        /// */
        ///function BootstrapUpload(params) { [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapUpload_js {
            get {
                return ResourceManager.GetString("BootstrapUpload_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .control-group.has-error .bs-upload-for {
        ///    .uneditable-input,
        ///    .browse,
        ///    .clear {
        ///        border-color: #b94a48;
        ///    }
        ///}
        ///
        ///.bs-upload-for {
        ///    .display.pretend-link {
        ///        color: blue;
        ///        text-decoration: underline;
        ///        cursor: pointer;
        ///    }
        ///}.
        /// </summary>
        public static string BootstrapUpload_less {
            get {
                return ResourceManager.GetString("BootstrapUpload_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetBootstrapVirtualModalWindow(id) {
        ///    return window[id + &apos;_bootstrapVirtualModalWindow&apos;];
        ///}
        ///
        ///function BootstrapVirtualModalWindow(params) {
        ///    this.id = params.id;
        ///    this.title = params.title;
        ///    this.frameUrl = params.frameUrl;
        ///    this.frameHeight = params.frameHeight;
        ///    this.incCloseButton = params.incCloseButton;
        ///    this.buttons = params.buttons;
        ///    this.closeEvents = new Array();
        ///    
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///BootstrapVirtualModalWindow.pro [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BootstrapVirtualModalWindow_js {
            get {
                return ResourceManager.GetString("BootstrapVirtualModalWindow_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @font-face {
        ///    font-family: &apos;ProximaNovaRegular&apos;;
        ///    src: url(&apos;Regular.eot&apos;);
        ///    src: url(&apos;Regular.eot?#iefix&apos;) format(&apos;embedded-opentype&apos;),
        ///         url(&apos;Regular.woff&apos;) format(&apos;woff&apos;),
        ///         url(&apos;Regular.ttf&apos;) format(&apos;truetype&apos;),
        ///         url(&apos;Regular.svg#ProximaNovaSoftRegular&apos;) format(&apos;svg&apos;);
        ///    font-weight: normal;
        ///    font-style: normal;
        ///}
        ///
        ///@font-face {
        ///    font-family: &apos;ProximaNovaMedium&apos;;
        ///    src: url(&apos;Medium.eot&apos;);
        ///    src: url(&apos;Medium.eot?#iefix&apos;) format(&apos;embedded-opentype&apos;),        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fonts_less {
            get {
                return ResourceManager.GetString("fonts_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;no&quot;?&gt;
        ///&lt;!DOCTYPE svg PUBLIC &quot;-//W3C//DTD SVG 1.1//EN&quot; &quot;http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd&quot; &gt;
        ///&lt;svg xmlns=&quot;http://www.w3.org/2000/svg&quot;&gt;
        ///&lt;metadata&gt;&lt;/metadata&gt;
        ///&lt;defs&gt;
        ///&lt;font id=&quot;glyphicons_halflingsregular&quot; horiz-adv-x=&quot;1200&quot; &gt;
        ///&lt;font-face units-per-em=&quot;1200&quot; ascent=&quot;960&quot; descent=&quot;-240&quot; /&gt;
        ///&lt;missing-glyph horiz-adv-x=&quot;500&quot; /&gt;
        ///&lt;glyph /&gt;
        ///&lt;glyph /&gt;
        ///&lt;glyph unicode=&quot;&amp;#xd;&quot; /&gt;
        ///&lt;glyph unicode=&quot; &quot; /&gt;
        ///&lt;glyph unicode=&quot;*&quot; d=&quot;M100 500v200h259l-183 183l141 141l183 -183v259h200v-259l [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GlyphiconsHalflingsReguarSvg {
            get {
                return ResourceManager.GetString("GlyphiconsHalflingsReguarSvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularEot {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularEot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularTtf {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularTtf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] GlyphiconsHalflingsRegularWoff {
            get {
                object obj = ResourceManager.GetObject("GlyphiconsHalflingsRegularWoff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v1.10.2 | (c) 2005, 2013 jQuery Foundation, Inc. | jquery.org/license
        /////@ sourceMappingURL=jquery-1.10.2.min.map
        ///*/
        ///(function(e,t){var n,r,i=typeof t,o=e.location,a=e.document,s=a.documentElement,l=e.jQuery,u=e.$,c={},p=[],f=&quot;1.10.2&quot;,d=p.concat,h=p.push,g=p.slice,m=p.indexOf,y=c.toString,v=c.hasOwnProperty,b=f.trim,x=function(e,t){return new x.fn.init(e,t,r)},w=/[+-]?(?:\d*\.|)\d+(?:[eE][+-]?\d+|)/.source,T=/\S+/g,C=/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,N=/^(?:\s*(&lt;[\w\W]+&gt;)[^&gt;]*|#([\w-]*))$/,k=/^ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_min_js {
            get {
                return ResourceManager.GetString("jquery_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery UI - v1.11.0 - 2014-06-26
        ///* http://jqueryui.com
        ///* Includes: core.js, widget.js, mouse.js, position.js, draggable.js, droppable.js, resizable.js, selectable.js, sortable.js, accordion.js, autocomplete.js, button.js, datepicker.js, dialog.js, menu.js, progressbar.js, selectmenu.js, slider.js, spinner.js, tabs.js, tooltip.js, effect.js, effect-blind.js, effect-bounce.js, effect-clip.js, effect-drop.js, effect-explode.js, effect-fade.js, effect-fold.js, effect-highlight.js, effect-puff.js, effect-pul [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_ui_min_js {
            get {
                return ResourceManager.GetString("jquery_ui_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] LayoutView_cshtml {
            get {
                object obj = ResourceManager.GetObject("LayoutView_cshtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Affected server may require a restart..
        /// </summary>
        public static string MessageServerRestart {
            get {
                return ResourceManager.GetString("MessageServerRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdditionalInfo.
        /// </summary>
        public static string MessageTitleAdditionalInfo {
            get {
                return ResourceManager.GetString("MessageTitleAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Bold_webfont_eot {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Bold_webfont_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Bold_webfont_svg {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Bold_webfont_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Bold_webfont_ttf {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Bold_webfont_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Bold_webfont_woff {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Bold_webfont_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Medium_webfont_eot {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Medium_webfont_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Medium_webfont_svg {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Medium_webfont_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Medium_webfont_ttf {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Medium_webfont_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Medium_webfont_woff {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Medium_webfont_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Regular_webfont_eot {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Regular_webfont_eot", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Regular_webfont_svg {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Regular_webfont_svg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Regular_webfont_ttf {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Regular_webfont_ttf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ProximaNovaSoft_Regular_webfont_woff {
            get {
                object obj = ResourceManager.GetObject("ProximaNovaSoft_Regular_webfont_woff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] SearchBarView_cshtml {
            get {
                object obj = ResourceManager.GetObject("SearchBarView_cshtml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function StdThemeSearchBar() {
        ///    return window[&apos;stdThemeSearchBar&apos;];
        ///}
        ///
        ///function StdThemeSearchBar() {
        ///    this.ignoreLoadingScreenElements = new Array();
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///StdThemeSearchBar.prototype.searchRowOpen = false;
        ///
        ///StdThemeSearchBar.prototype.searchRowChanging = false;
        ///
        ///StdThemeSearchBar.prototype.searchRowNormalBg = &apos;#f0f0f0&apos;;
        ///
        ///StdThemeSearchBar.prototype.searchRowHightlightBg = &apos;#e8e8e8&apos;;
        ///
        ///StdThemeSearchBar.prototype.searchRowDefaultHeight = [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StdThemeSearchBar_js {
            get {
                return ResourceManager.GetString("StdThemeSearchBar_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .template-search-row {
        ///    border-bottom: 1px solid #af4e8b;
        ///    margin-top: -81px;
        ///    padding-top: 8px;
        ///    z-index: 1000;
        ///    width: 100%;
        ///    overflow: hidden;
        ///
        ///    .opacity-box {
        ///        background-color: #f0f0f0;
        ///        width: 100%;
        ///        height: 100%;
        ///        position: absolute;
        ///        opacity: .9;
        ///        top: 0;
        ///    }
        ///
        ///    .search-bar-buttons {
        ///        text-align: right;
        ///    }
        ///
        ///    .close-search-bar {
        ///        text-align: center;
        ///        display: block;
        ///        width: 100 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StdThemeSearchBar_less {
            get {
                return ResourceManager.GetString("StdThemeSearchBar_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function GetStdThemeTemplate() {
        ///    return window[&apos;stdThemeTemplate&apos;];
        ///}
        ///
        ///function StdThemeTemplate() {
        ///    this.ignoreLoadingScreenElements = new Array();
        ///
        ///    $(document).ready($.proxy(this.init, this));
        ///}
        ///
        ///StdThemeTemplate.prototype.initCloseResults = 0;
        ///
        ///StdThemeTemplate.prototype.lastClickElement = null;
        ///
        ////*
        /// * Links and buttons in the interface will usually show the &quot;Working...&quot;
        /// * window when clicked. Any elements that are added to this array
        /// * will not engage the window (when clic [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StdThemeTemplate_js {
            get {
                return ResourceManager.GetString("StdThemeTemplate_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @heroColor: #f18e00;
        ///@heroHightlightColor: #af4e8b;
        ///
        ///html {
        ///  overflow-x: hidden; /* Prevent scroll on narrow devices */
        ///}
        ///body {
        ///  padding-bottom: 70px;
        ///}
        ///
        ////*
        /// * Off Canvas
        /// * --------------------------------------------------
        /// */
        ///@media screen and (max-width: 767px) {
        ///  .row-offcanvas {
        ///    position: relative;
        ///    -webkit-transition: all 0.25s ease-out;
        ///    -moz-transition: all 0.25s ease-out;
        ///    transition: all 0.25s ease-out;
        ///  }
        ///
        ///  .row-offcanvas-left
        ///  .sidebar-offcanvas {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string StdThemeTemplate_less {
            get {
                return ResourceManager.GetString("StdThemeTemplate_less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap trooper_png {
            get {
                object obj = ResourceManager.GetObject("trooper_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Identity user name cannot be null. User name not found in HttpContext or Windows Identity..
        /// </summary>
        public static string WindowsIdentityUsernameCannotBeNull {
            get {
                return ResourceManager.GetString("WindowsIdentityUsernameCannotBeNull", resourceCulture);
            }
        }
    }
}
